13.1 add-controllers
KukushkinIgorA/java-shareit pull request #2
Opened 2023-01-25 17:46 UTC by KukushkinIgorA

2023-01-25 19:07 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@Validated(Create.class) @RequestBody UserDto userDto) {
Если есть желание, добавь обработчик неверных входных данных, чтобы клиент получал красивое сообщение
{
	"error": "Ошибка bad request: Validation failed for argument [0] in public ru.practicum.shareit.user.dto.UserDto ru.practicum.shareit.user.UserController.create(ru.practicum.shareit.user.dto.UserDto) with 2 errors: [Field error in object 'userDto' on field 'name': rejected value [null]; codes [NotBlank.userDto.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.name,name]; arguments []; default message [name]]; default message [must not be blank]] [Field error in object 'userDto' on field 'email': rejected value [email3email.com]; codes [Email.userDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@38fe8cfa,.*]; default message [must be a well-formed email address]] "
}

2023-01-25 19:11 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/exception/handler/ErrorHandler.java
> +    public ErrorResponse handleValidationException(final ValidationException e) {
Попробуй объединить обработчики исключений https://www.baeldung.com/exception-handling-for-rest-with-spring

2023-01-25 19:11 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Похоже эта TODO  уже лишняя.

2023-01-25 19:13 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") int userId,
Постарайся выносить константы и использовать везде константы, тогда менять придется в одном месте. Когда нажимаешь ctrl+c/ctrl+v всегда думай о том как можно избежать дублирования и в скольких местах придется править, когда нужно будет внести изменение, а изменения бывают очень часто

2023-01-25 19:17 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Есть несколько предложений по улучшению кода

2023-01-30 10:33 UTC, KukushkinIgorA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Убрал все TODO Sprint add-controllers.

2023-01-30 10:35 UTC, KukushkinIgorA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") int userId,
Перенес в константу X_SHARER_USER_ID = "X-Sharer-User-Id";

2023-01-30 11:37 UTC, KukushkinIgorA commented on src/main/java/ru/practicum/shareit/exception/handler/ErrorHandler.java
> +    public ErrorResponse handleValidationException(final ValidationException e) {
Объединил ошибки по HttpStatus

2023-01-30 11:39 UTC, KukushkinIgorA commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@Validated(Create.class) @RequestBody UserDto userDto) {
Поправлю в следующих спринтах

2023-01-30 18:27 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо.

2023-02-02 12:31 UTC, merged