14.1 add-bookings before review
KukushkinIgorA/java-shareit pull request #3
Opened 2023-02-15 10:47 UTC by KukushkinIgorA

2023-02-15 19:11 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private LocalDateTime created;
Попробуй на полях с датами использовать аннотацию JsonFormat

2023-02-15 19:11 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private LocalDateTime created;
Это необязательное предложение

2023-02-15 19:15 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingGetState bookingGetState = BookingGetState.from(bookingGetStateString).orElseThrow(() ->
Проверку на то, что state приходит верный лучше вынести в отдельную функцию и не дулбировать код в каждом методе

2023-02-15 19:20 UTC, EvgenyKoptubenko commented
Система позволяет добавить пользователей с одинаковыми email.
Если такого требования не было в ТЗ, тогда можно не делать

2023-02-15 19:21 UTC, EvgenyKoptubenko commented
Если удаляется пользователь, которого нет, то клиенту приходит 500
{
	"error": "Произошла непредвиденная ошибка: No class ru.practicum.shareit.user.model.User entity with id 2222 exists!"
}
Но на самом деле это не ошибка на стороне сервера, а просто данных нет. Может быть 404 тут будет лучше

2023-02-15 19:22 UTC, EvgenyKoptubenko commented
Если приходит запрос на создание пользователя с плохим email, то клиент получает слишком длинное сообщение об ошибке
{
	"error": "Ошибка MethodArgumentNotValidException: Validation failed for argument [0] in public ru.practicum.shareit.user.dto.UserDto ru.practicum.shareit.user.UserController.create(ru.practicum.shareit.user.dto.UserDto) with 2 errors: [Field error in object 'userDto' on field 'name': rejected value [null]; codes [NotBlank.userDto.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.name,name]; arguments []; default message [name]]; default message [must not be blank]] [Field error in object 'userDto' on field 'email': rejected value [email3email.com]; codes [Email.userDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@6d831ba,.*]; default message [must be a well-formed email address]] "
}

2023-02-15 19:24 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Есть немного предложений по улучшению, если есть желание.

2023-02-17 10:16 UTC, KukushkinIgorA commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private LocalDateTime created;
Сделал частично
@JsonFormat(shape = JsonFormat.Shape.STRING)

2023-02-17 10:16 UTC, KukushkinIgorA commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingGetState bookingGetState = BookingGetState.from(bookingGetStateString).orElseThrow(() ->
Done

2023-02-17 10:17 UTC, KukushkinIgorA commented
> Система позволяет добавить пользователей с одинаковыми email. Если такого требования не было в ТЗ, тогда можно не делать



> Система позволяет добавить пользователей с одинаковыми email. Если такого требования не было в ТЗ, тогда можно не делать

	Проверил. С одинаковыми email не позволяет, срабатывает constrain на таблице
	SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
	С одинаковым name можно создать, но такого требования по name нету

2023-02-17 10:18 UTC, KukushkinIgorA commented
> Если удаляется пользователь, которого нет, то клиенту приходит 500 { "error": "Произошла непредвиденная ошибка: No class ru.practicum.shareit.user.model.User entity with id 2222 exists!" } Но на самом деле это не ошибка на стороне сервера, а просто данных нет. Может быть 404 тут будет лучше

Поправил

2023-02-17 10:19 UTC, KukushkinIgorA commented
> Если приходит запрос на создание пользователя с плохим email, то клиент получает слишком длинное сообщение об ошибке { "error": "Ошибка MethodArgumentNotValidException: Validation failed for argument [0] in public ru.practicum.shareit.user.dto.UserDto ru.practicum.shareit.user.UserController.create(ru.practicum.shareit.user.dto.UserDto) with 2 errors: [Field error in object 'userDto' on field 'name': rejected value [null]; codes [NotBlank.userDto.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.name,name]; arguments []; default message [name]]; default message [must not be blank]] [Field error in object 'userDto' on field 'email': rejected value [email3email.com]; codes [Email.userDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@6d831ba,.*]; default message [must be a well-formed email address]] " }

Тут удалось только добавить кастомное сообщение
[@Email](https://app.pachca.com/chats/4512429?discussion_sidebar=details#)(groups = {Create.class, Update.class}, message = "Не валидный email")

2023-02-17 17:17 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-20 05:07 UTC, merged