16.1 add-docker before review
KukushkinIgorA/java-shareit pull request #5
Opened 2023-03-05 19:16 UTC by KukushkinIgorA

2023-03-05 20:25 UTC, EvgenyKoptubenko commented
Есть замечания с прошлых итераций
Например, если добавить второго такого же пользователя, то приходит 500-й ответ
{
	"error": "Произошла непредвиденная ошибка: could not execute statement; SQL [n/a]; constraint [uq_user_email]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}

2023-03-05 20:26 UTC, EvgenyKoptubenko commented
Слишком большое сообщение об ошибке при добавлении пользователя с неверной почтой

{
	"error": "Ошибка MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> ru.practicum.shareit.user.UserController.create(ru.practicum.shareit.user.dto.UserDto) with 2 errors: [Field error in object 'userDto' on field 'name': rejected value [null]; codes [NotBlank.userDto.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.name,name]; arguments []; default message [name]]; default message [must not be blank]] [Field error in object 'userDto' on field 'email': rejected value [email3email.com]; codes [Email.userDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@6dc01782,.*]; default message [Не валидный email]] "
}

2023-03-05 20:27 UTC, EvgenyKoptubenko requested changes
По докеру замечаний нет. Работа сделана хорошо. Если есть желание, поправь несколько предложений по улучшению кода

2023-03-06 08:43 UTC, KukushkinIgorA commented
> 



> Есть замечания с прошлых итераций Например, если добавить второго такого же пользователя, то приходит 500-й ответ { "error": "Произошла непредвиденная ошибка: could not execute statement; SQL [n/a]; constraint [uq_user_email]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement" }



> Есть замечания с прошлых итераций Например, если добавить второго такого же пользователя, то приходит 500-й ответ { "error": "Произошла непредвиденная ошибка: could not execute statement; SQL [n/a]; constraint [uq_user_email]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement" }

Поправил, теперь будет status 409

2023-03-06 08:44 UTC, KukushkinIgorA commented
> Слишком большое сообщение об ошибке при добавлении пользователя с неверной почтой
> 
> { "error": "Ошибка MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> ru.practicum.shareit.user.UserController.create(ru.practicum.shareit.user.dto.UserDto) with 2 errors: [Field error in object 'userDto' on field 'name': rejected value [null]; codes [NotBlank.userDto.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.name,name]; arguments []; default message [name]]; default message [must not be blank]] [Field error in object 'userDto' on field 'email': rejected value [email3email.com]; codes [Email.userDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@6dc01782,.*]; default message [Не валидный email]] " }

Чуть укоротил

2023-03-06 18:28 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо.

2023-03-07 04:49 UTC, merged